### PR TITLE
BUG: RMath library uses shape/scale parameterization of Gamma dist not shape/rate

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by danielcsaba** [comment]
hi @sglyon !

I think the idea was to follow the API of the Julia library which is using the [shape/scale](http://distributionsjl.readthedocs.io/en/latest/univariate-continuous.html#Gamma) setup instead of Wikipedia which is following the [shape/rate](https://en.wikipedia.org/wiki/Gamma_distribution) one. I don't have a strong preference so happy to go either way

**Comment by sglyon** [comment]
I believe that wikipedia has both

And I'm pretty confident that Distributions.jl and RMath are both using shape/scale and not shape/rate. See [here for the Rmath](https://github.com/QuantEcon/rvlib/blob/22285d19eda9d3d8519facdedfa891f95e9f5f7f/src/dgamma.c#L33-L34) and [here for the Julia](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/gamma.jl#L4-L5) (also [here](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/gamma.jl#L59) for the mean of the Gamma distribution -- compare to wikipedia's definition of the mean when using shape/scale)

**Comment by danielcsaba** [comment]
I agree with all those and see the confusion now. I thought we were using shape/scale from the get go.
Thanks for pointing it out!

**Comment by sglyon** [comment]
Ahh ok that makes more sense.

Ok cool, glad you agree!

**Pull request merged**
